import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GroupProvider } from "./context/GroupContext";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F2EFE7] text-[#006A71] min-h-screen">
        <Navbar />
        <div className="pt-6">
          <GroupProvider>
            {children}
          </GroupProvider>
        </div>
      </body>
    </html>
  );
}
